### ISSUE TITLE
Linode provider duplicates "*" subdomain record

### ISSUE THREAD

**Issue by drewgingerich** [TimothyYe/godns#146]
**Describe the bug**  
When using the Linode provider with a subdomain named "*",  duplicate DNS records are created.

**The frequency of this issue**  
This issue is easy to reproduce.

**Your GoDNS configuration** 
```yml
{
  "provider": "Linode",
  "login_token": "<redacted>",
  "domains": [
    {
      "domain_name": "godns.test",
      "sub_domains": ["@", "*", "minecraft"]
    }
  ],
  "ip_url": "https://icanhazip.com/",
  "ip_type": "IPv4",
  "interval": 5,
  "resolver": "8.8.8.8",
  "debug_info": true,
}

```

**Expected behavior**  
Only one DNS record should be created for the "*" subdomain.

**Screenshots**  
<img width="1266" alt="Screen Shot 2022-04-11 at 6 23 45 PM" src="https://user-images.githubusercontent.com/15133892/162860095-33e2ff86-fd84-420e-872f-d72bcc1e4c72.png">

**Additional context**  
I've already know the source of the problem and wanted to make this issue to track it. It is due to a bug in the Linode API that makes it unable to find a subdomain when it's named "*". I've contacted Linode support and opened a ticket, but it may be a while.
