### ISSUE TITLE
Invalid request headers - Cloudflare

### ISSUE THREAD

**Issue by bashfulrobot** [TimothyYe/godns#49]
Hi there,

I'm running the app in docker.

```
docker version                                                         ─╯
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.13.4
 Git commit:        1752eb3
 Built:             Sat Nov 16 01:05:26 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       9552f2b
  Built:            Sat Nov 16 01:07:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Using the following `docker-compose` file:

```
---
version: "2"
services:
  godns:
    image: timothyye/godns
    container_name: godns
    volumes:
      - /home/dustin/docker/godns/config.json:/usr/local/godns/config.json
    restart: unless-stopped
```

My godns config file looks like:

```
cat config.json                                                        ─╯
{
    "provider": "Cloudflare",
    "email": "xxxxx@xxxxx.com",
    "password": "xxxxxxxxxxx",
    "domains": [
        {
            "domain_name": "xxxxxxxx.com",
            "sub_domains": [
                "xxxxx"
            ]
        }
    ],
    "ip_url": "https://myip.biturl.top",
    "interval": 300,
    "socks5_proxy": ""
}
```

After starting with `docker-compose -d up` I then have a look at the logs with `docker logs --tail 50 --follow --timestamps godns`. I then see the following error:

```
2020-01-03T22:45:04.007390136Z [GoDNS] 2020/01/03 22:45:04 Response failed: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
```

Any suggestions?

*EDIT*
PS Thank you!
